CREATE TABLE gyms (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL UNIQUE,
    address      VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(25)                             NOT NULL,

    CONSTRAINT pk_gyms PRIMARY KEY (id)
);