CREATE TABLE membership_plans (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    gym_id          BIGINT                                  NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    type            VARCHAR(255)                            NOT NULL,
    amount          DECIMAL(15, 2)                          NOT NULL,
    currency_code   VARCHAR(3)                              NOT NULL,
    duration_months INT                                     NOT NULL,
    max_members     INT                                     NOT NULL,

    CONSTRAINT pk_membership_plans PRIMARY KEY (id)
);

ALTER TABLE membership_plans
    ADD CONSTRAINT FK_MEMBERSHIP_PLANS_ON_GYM
    FOREIGN KEY (gym_id)
    REFERENCES gyms (id)
    ON DELETE CASCADE;