CREATE TABLE members
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    membership_plan_id BIGINT                                  NOT NULL,
    full_name          VARCHAR(255)                            NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    start_date         TIMESTAMP                               NOT NULL,
    status             VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_members PRIMARY KEY (id)
);

ALTER TABLE members
    ADD CONSTRAINT FK_MEMBERS_ON_MEMBERSHIP_PLAN
    FOREIGN KEY (membership_plan_id)
    REFERENCES membership_plans (id);